title: Lily theme
description: A fresh Jekyll theme based on Beercss.
show_downloads: true
google_analytics:
theme: jekyll-theme-lily
remote-theme: HowerZiu/jekyll-theme-lily

lily:
  beercss:
    css_url:
    js_url:
